# k6-resource.yml

apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6httpsample
spec:
  parallelism: 4
  script:
    configMap:
      name: k6-http-test
      file: httpSampleRequest.js
  arguments: --out json=my_test_result.json   
  separate: false
  runner:
    image: loadimpact/k6:latest
    metadata:
      labels:
        cool-label: foo
      annotations:
        cool-annotation: bar
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
    resources:
      limits:
        cpu: 200m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
  starter:
    image: loadimpact/k6:latest
    metadata:
      labels:
        cool-label: foo
      annotations:
        cool-annotation: bar
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
      runAsNonRoot: true