# k6-resource.yml

apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6httpsample
spec:
  parallelism: 4
  script:
    localFile : test/httpSampleRequest.js
  #arguments: --out json=test/my_test_result.json   
  separate: false
  runner:
    image: lcsdigitaldev.azurecr.io/k6-http/k6-http-test:v1.0.9-SNAPSHOT
    metadata:
      labels:
        cool-label: foo
      annotations:
        cool-annotation: bar
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
      runAsNonRoot: true
    resources:
      limits:
        cpu: 200m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
  starter:
    metadata:
      labels:
        cool-label: foo
      annotations:
        cool-annotation: bar
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
      runAsNonRoot: true